DIRSRCBACKEND := proyect/backend/
DIRSRCFRONTEND := proyect/frontend/

CFLAGS := -m
LDLIBS := aaa
CCBACKEND := python
CCFRONTEND := npm

TEST:= test_kodiApi.py

all : runbackend runfrontend

runbackend: venvbackend
	flask run

venvbackend:
	./$(DIRSRCBACKEND)/pipenv shell
	./$(DIRSRCBACKEND)/proyect/ export FLASK_APP="main.py"

runfrontend:
	./$(DIRSRCFRONTEND)/ $(CCFRONTEND) run serve

test:
	./$(DIRSRCBACKEND)/proyect/ $(CCBACKEND) -m unittest -v $(TEST)

